### ISSUE TITLE
mqsicreatebar not found

### ISSUE THREAD

**Issue by tsutsarin-fuib** [dennisseidel/iib-bestpractice-runtimes#10]
I sourced mqsiprofile.
For packaging BARs there's only `mqsipackagebar`, the `mqsicreatebar` is not found.
I'm new to IIB and this image, am I missing something?
I tried both base and mq-client images.

The command I used to start container:
`docker run --rm -it -e IIB_LICENSE=accept --entrypoint bash dennisseidel/iib-bestpractice-runtimes:10.0.0.8-mqclient`

**Comment by dennisseidel** [comment]
@tsutsarin-fuib Hi image does currently not support the mounting of code and the create of the bar file inside the container. 

What you can do is the following steps: 
1. Build the bar file external
2. Create a dockerfile that inherits from ```dennisseidel/iib-bestpractice-runtimes:10.0.0.8-mqclient``` and that copies your barflies into the image ```COPY workspace/BARfiles/app.bar /iibProjects/``` in the how to section described

**Comment by tsutsarin-fuib** [comment]
Thanks!

What if I make PR that includes Dockerfile with IBM Integration Toolkit for building bars inside the container?

**Comment by dennisseidel** [comment]
@tsutsarin-fuib Then we can merge it into the repo, and I think I / many people would be very thankful :-) 

I planned on have such an image anyway not for running in in production, but for the build step in the DevOps Pipeline. So that would be great.

**Comment by dennisseidel** [comment]
Can be reopend if problem is still relevant.
